name: jjCheckInScript

# ç¯å¢ƒå˜é‡
env:
  COOKIE: ${{ secrets.COOKIE }}
  PASS: ${{ secrets.PASS }}

  run: echo 'try to show secret ğŸ˜‰' && echo $COOKIE && echo $PASS

on:
  push:
  # ä»£ç æ¨é€åˆ° main åˆ†ä¹‹æ—¶è‡ªåŠ¨æ‰§è¡Œ
    branches: [ 'main' ]
  # # å®šæ—¶æ‰§è¡Œ
  # schedule:
  #   # æ¯å¤©9ç‚¹æ‰§è¡Œ æ—¶é—´æ ¼å¼ minute hour day month week è®¾ç½®çš„æ—¶é—´æ˜¯UTC ä¸æ˜¯åŒ—äº¬æ—¶é—´ éœ€è¦+8
  #   - cron: "0 1 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start:
    # è¿è¡Œç¯å¢ƒä¸ºæœ€æ–°ç‰ˆçš„Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  

      #å®‰è£…node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2  
        with:
          node-version: '14'

      # å®‰è£…ä¾èµ–å¹¶ä¸”æ‰§è¡Œè„šæœ¬
      - name: npm install
        run: npm install
      
      - name: Start task
        run: node index.js
